/* This file is auto-generated by Cbindgen. */

#pragma once

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

typedef enum DataType {
        Boolean = 0,
        I8 = 1,
        I16 = 2,
        I32 = 3,
        I64 = 4,
        U8 = 5,
        U16 = 6,
        U32 = 7,
        U64 = 8,
        F32 = 9,
        F64 = 10,
        Binary = 11,
        String = 12,
        TimestampSecond = 15,
        TimestampMillisecond = 16,
        TimestampMicrosecond = 17,
        TimestampNanosecond = 18,
} DataType;

typedef enum SemanticType {
        Tag = 0,
        Field,
        Timestamp,
} SemanticType;

typedef enum StatusCode {
        Success = 0,
        Err = 1,
} StatusCode;

typedef struct Client Client;

/**
 * The [`RowBatch`] struct contains the data to be inserted.
 */
typedef struct RowBatch RowBatch;

typedef struct ClientOptions {
        const char *endpoint;
        const char *db_name;
        bool secure;
} ClientOptions;

typedef struct ColumnSchema {
        const char *name;
        enum DataType data_type;
        enum SemanticType semantic_type;
} ColumnSchema;

typedef enum Value_Tag {
        BoolValue,
        I8Value,
        I16Value,
        I32Value,
        I64Value,
        U8Value,
        U16Value,
        U32Value,
        U64Value,
        F32Value,
        F64Value,
        StringValue,
        BinaryValue,
        TimestampValueSecond,
        TimestampValueMillisecond,
        TimestampValueMicrosecond,
        TimestampValueNanosecond,
        BoolValueNull,
        I8ValueNull,
        I16ValueNull,
        I32ValueNull,
        I64ValueNull,
        U8ValueNull,
        U16ValueNull,
        U32ValueNull,
        U64ValueNull,
        F32ValueNull,
        F64ValueNull,
        StringValueNull,
        BinaryValueNull,
        TimestampValueSecondNull,
        TimestampValueMillisecondNull,
        TimestampValueMicrosecondNull,
        TimestampValueNanosecondNull,
} Value_Tag;

typedef struct BinaryValue_Body {
        const void *_0;
        size_t _1;
} BinaryValue_Body;

typedef struct Value {
        Value_Tag tag;
        union {
                struct {
                        char bool_value;
                };
                struct {
                        char i8_value;
                };
                struct {
                        short i16_value;
                };
                struct {
                        int i32_value;
                };
                struct {
                        long i64_value;
                };
                struct {
                        unsigned char u8_value;
                };
                struct {
                        unsigned short u16_value;
                };
                struct {
                        unsigned int u32_value;
                };
                struct {
                        unsigned long u64_value;
                };
                struct {
                        float f32_value;
                };
                struct {
                        double f64_value;
                };
                struct {
                        const char *string_value;
                };
                BinaryValue_Body binary_value;
                struct {
                        long timestamp_value_second;
                };
                struct {
                        long timestamp_value_millisecond;
                };
                struct {
                        long timestamp_value_microsecond;
                };
                struct {
                        long timestamp_value_nanosecond;
                };
        };
} Value;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new client for ingesting data into GreptimeDB.
 *
 * # Safety
 *
 * The `client_ptr` must be a valid pointer.
 */
enum StatusCode client_new(struct ClientOptions opts,
                           struct Client **client_ptr);

/**
 * Insert [`RowBatch`] into the GreptimeDB.
 *
 * # Safety
 *
 * Caller must ensure that `client_ptr` and `row_batch_ptr` are valid pointers.
 */
enum StatusCode client_insert_row_batch(struct RowBatch *row_batch_ptr,
                                        struct Client *client_ptr);

/**
 * Release the client and free the memory.
 *
 * # Safety
 *
 * Caller must ensure that `client_ptr` is a valid pointer to a [`Client`].
 */
void client_free(struct Client *client_ptr);

/**
 * Create a new [`RowBatch`] with pre-allocate, and assign it to `row_batch_ptr`.
 *
 * # Safety
 *
 * The row_batch_ptr must be a valid pointer.
 */
enum StatusCode row_batch_new_with_capacity(const char *table_name,
                                            uintptr_t capacity,
                                            const struct ColumnSchema *column_schema_ptr,
                                            uintptr_t len,
                                            struct RowBatch **row_batch_ptr);

/**
 * Push a row to the [`RowBatch`].
 *
 * # Note
 *
 * There is no schema validation here. The caller must ensure that the
 * `value_ptr` and `len` match the schema.
 *
 * # Safety
 *
 * The `value_ptr` and `len` must identify a valid [`Value`] array. And
 * `row_batch_ptr` must be a valid pointer to a [`RowBatch`].
 */
enum StatusCode row_batch_push_row(struct Value *value_ptr,
                                   uintptr_t len,
                                   struct RowBatch *row_batch_ptr);

/**
 * Release the [`RowBatch`] and free the memory.
 *
 * # Safety
 *
 * The `row_batch_ptr` must be a valid pointer to a [`RowBatch`].
 */
enum StatusCode row_batch_free(struct RowBatch *row_batch_ptr);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
